name: Build and Test

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - master

jobs:
  web_test:
    name: Web Test
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./outline_client/package-lock.json

      - name: Install NPM Dependencies
        run: cd outline_client && npm ci

      - name: Run Linter
        run: ./outline_apps outline_client lint

      - name: Build Web App
        run: ./outline_apps outline_client www/build

      - name: Test Web App
        run: ./outline_apps outline_client www/test

      - uses: codecov/codecov-action@v3
        with:
          files: ./outline_client/output/coverage/www/coverage-final.json
          flags: unittests, www

  linux_debug_build:
    name: Linux Debug Build
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    needs: web_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./outline_client/package-lock.json

      - name: Install NPM Dependencies
        run: cd outline_client && npm ci

      - name: Build Linux Client
        run: ./outline_apps outline_client electron/build linux

  windows_debug_build:
    name: Windows Debug Build
    runs-on: windows-2019
    timeout-minutes: 10
    needs: web_test
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./outline_client/package-lock.json

      - name: Install NPM Dependencies
        run: cd outline_client && npm ci

      - name: Build Windows Client
        run: ./outline_apps outline_client electron/build windows

  macos_debug_build:
    name: MacOS Debug Build
    runs-on: macos-13
    timeout-minutes: 20
    needs: web_test
    steps:
      - name: Display XCode
        run: xcode-select --print-path

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./outline_client/package-lock.json

      - name: Install NPM Dependencies
        run: cd outline_client && npm ci

      - name: Test OutlineAppleLib
        run: ./outline_apps outline_client cordova/test macos

      - name: Build MacOS Client
        run: ./outline_apps outline_client cordova/build macos

      - uses: codecov/codecov-action@v3
        with:
          xcode: true
          xcode_archive_path: ./outline_client/output/coverage/apple/macos/TestResult.xcresult
          flags: unittests, apple, macos

  ios_debug_build:
    name: iOS Debug Build
    runs-on: macos-13
    timeout-minutes: 20
    needs: web_test
    steps:
      - name: Display XCode
        run: xcode-select --print-path

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./outline_client/package-lock.json

      - name: Install NPM Dependencies
        run: cd outline_client && npm ci

      - name: Test OutlineAppleLib
        run: ./outline_apps outline_client cordova/test ios

      - name: Build iOS Client
        run: ./outline_apps outline_client cordova/build ios

      - uses: codecov/codecov-action@v3
        with:
          xcode: true
          xcode_archive_path: ./outline_client/output/coverage/apple/ios/TestResult.xcresult
          flags: unittests, apple, ios

  android_debug_build:
    name: Android Debug Build
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    needs: web_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./outline_client/package-lock.json

      - name: Install NPM Dependencies
        run: cd outline_client && npm ci

      - name: Install Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Setup Android
        run: bash ./outline_client/tools/build/setup_linux_android.sh

      - name: Build Android Client
        run: ./outline_apps outline_client cordova/build android -- --verbose
